/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as init from "./init";
export * as speak from "./speak";
export * as finish from "./finish";