/**
 * @packageDocumentation
 * @module api.functional.speak
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, IPropagation, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { SpeakToInterviewerData, SpeakToInterviewerException, SpeakToInterviewerView } from "../../../primary/speak-to-interviewer/speak-to-interviewer.data";

/**
 * 면접관에게 대답하기.
 * 
 * @tag Interview
 * @security secret
 * @param data req body
 * @return response type
 * @throws 400
 * 
 * @controller AppController.speakToInterviewer
 * @path POST /speak
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function speakToInterviewer(
    connection: IConnection,
    data: speakToInterviewer.Input,
): Promise<speakToInterviewer.Output> {
    return PlainFetcher.propagate(
        {
            ...connection,
            headers: {
                ...(connection.headers ?? {}),
                "Content-Type": "application/json",
            },
        },
        {
            ...speakToInterviewer.METADATA,
            path: speakToInterviewer.path(),
        } as const,
        data,
    );
}
export namespace speakToInterviewer {
    export type Input = Primitive<SpeakToInterviewerData>;
    export type Output = IPropagation<{
        201: SpeakToInterviewerView;
        400: SpeakToInterviewerException;
    }>;

    export const METADATA = {
        method: "POST",
        path: "/speak",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/speak`;
    }
}